## Kubernetes Fundamentals labs v1.4.5
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-standard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
